### ISSUE TITLE
Crash while trying to run

### ISSUE THREAD

**Issue by Lagomorpheux** [josemmo/plagpatrol#27]
Terminal output:

> (node:13068) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[13068:0716/110056.501934:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

This was on release [v0.0.9](https://github.com/josemmo/plagpatrol/releases/tag/v0.0.9), deb package, running on Ubuntu 23.04 (lunar).

I don't know why GPU is mentioned, but I have a NVIDIA GeForce GTX 1650 using the proprietary driver nvidia-driver-525.

**Comment by josemmo** [comment]
Hello @Lagomorpheux,

This project is unmaintained and won't receive further updates.

You can still use the web version at https://josemmo.github.io/plagpatrol/.
