### ISSUE TITLE
only for pdf?

### ISSUE THREAD

**Issue by OrionRandD** [josemmo/plagpatrol#4]
Does this tool checks for other documents than pdf?
Does it check .md .txt .doc .docx etc...?
Thx a lot

**Comment by josemmo** [comment]
Plagpatrol uses [mozilla/pdf.js](https://github.com/mozilla/pdf.js) to parse the documents. As the name suggests, it only supports PDF files, and AFAIK there's no other well-stablished library for reading and rendering Microsoft Office documents.

**Comment by OrionRandD** [comment]
Thx a lot :)

**Comment by josemmo** [comment]
Closing this for now, may be re-opened in the future if a good library for rendering and parsing Office documents comes up.
